apiVersion: apps/v1
kind: Deployment
metadata:
  name: shop-backend
spec:
  replicas: 3
  selector:
    matchLabels:
      app: shop-backend
  template:
    metadata:
      labels:
        app: shop-backend
    spec:
      containers:
        - name: shop-backend
          image: registry.gitlab.com/codelab-kubernetes/apps/shop-backend:database
          resources:
            limits:
              memory: "128Mi"
              cpu: "100m"
            requests:
              memory: "32Mi"
              cpu: "50m"
          ports:
            - containerPort: 8080
          env:
            - name: SPRING_R2DBC_URL
              value: "r2dbc:postgresql://shop-database:5432/shop"
          envFrom:
            - secretRef:
                name: shop-database-secret
