apiVersion: v1
kind: ConfigMap
metadata:
  name: shop-database-configmap
data:
  POSTGRES_DB: shop
---
apiVersion: v1
kind: Secret
metadata:
  name: shop-database-secret
stringData:
  POSTGRES_PASSWORD: shop
---
apiVersion: v1
kind: Service
metadata:
  name: shop-database-service
  labels:
    app: shop-database-label
spec:
  ports:
    - port: 5432
      targetPort: 5432
  clusterIP: None
  selector:
    app: shop-database-label
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: shop-database
spec:
  selector:
    matchLabels:
      app: shop-database-label
  serviceName: shop-database-service
  replicas: 1
  template:
    metadata:
      labels:
        app: shop-database-label
    spec:
      containers:
        - name: shop-database
          image: registry.gitlab.com/codelab-kubernetes/apps/shop-database:latest
          resources:
            limits:
              memory: "256Mi"
              cpu: "500m"
            requests:
              memory: "64Mi"
              cpu: "100m"
          ports:
            - containerPort: 5432
              name: web
          volumeMounts:
            - name: postgres-data
              mountPath: /var/lib/postgresql/data
              subPath: posgres
          envFrom:
            - configMapRef:
                name: shop-database-configmap
            - secretRef:
                name: shop-database-secret
  volumeClaimTemplates:
    - metadata:
        name: postgres-data
      spec:
        accessModes: ["ReadWriteOnce"]
        resources:
          requests:
            storage: 1Gi
