apiVersion: v1
kind: Service
metadata:
  name: shop-backend-service
spec:
  selector:
    app: shop-backend
  ports:
    - port: 8080
      targetPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: shop-frontend-service
spec:
  selector:
    app: shop-frontend
  ports:
    - port: 80
      targetPort: 80
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: shop-ingress
  annotations:
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
  labels:
    name: shop-ingress
spec:
  ingressClassName: nginx
  tls:
    - hosts:
        - student-48.devshop.codelab.dwidwi.tech
      secretName: tls
  rules:
    - host: student-48.devshop.codelab.dwidwi.tech
      http:
        paths:
          - pathType: Prefix
            path: "/"
            backend:
              service:
                name: shop-frontend-service
                port:
                  number: 80
          - pathType: Prefix
            path: "/api"
            backend:
              service:
                name: shop-backend-service
                port:
                  number: 8080
